version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./settings/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - srv-java-users
    command: /bin/bash -c "cp -f /etc/nginx/conf.d/site.conf.template /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  srv-java-users:
    image: gradle:alpine
    ports:
      - "8081"
    depends_on:
      - db-session
      - db-account
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: gradle run


  db-session:
    restart: always
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=jetty
      - POSTGRES_PASSWORD=jettypass
      - POSTGRES_DB=session
    volumes:
      - ./volumes/postgresql-session:/var/lib/postgresql-session

  db-account:
    restart: always
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=jetty
      - POSTGRES_PASSWORD=jettypass
      - POSTGRES_DB=account
    volumes:
      - ./settings/postgre/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes/postgresql-account:/var/lib/postgresql-account
