version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
        - db-session
        - db-account
    volumes:
      - /home/cherie/IdeaProjects/rest:/app
    entrypoint: ./gradlew clean run


  db-session:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5432"
    environment:
      - DEBUG=false

      - DB_USER=jetty
      - DB_PASS=jettypass
      - DB_NAME=session
    volumes:
      - /srv/docker/postgresql-session:/var/lib/postgresql-session

  db-account:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5432"
    environment:
      - DEBUG=false

      - DB_USER=jetty
      - DB_PASS=jettypass
      - DB_NAME=account
    volumes:
      - /srv/docker/postgresql-account:/var/lib/postgresql-account
