version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
        - db-session
        - db-account
    volumes:
      - /home/cherie/IdeaProjects/rest:/app
    entrypoint: ./gradlew clean run


  db-session:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jetty
      - POSTGRES_PASSWORD=jettypass
      - POSTGRES_DB=session
    volumes:
      - /srv/docker/postgresql-session:/var/lib/postgresql-session

  db-account:
    restart: always
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=jetty
      - POSTGRES_PASSWORD=jettypass
      - POSTGRES_DB=account
    volumes:
      - ./src/main/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /srv/docker/postgresql-account:/var/lib/postgresql-account
